apiVersion: v1
kind: Service
metadata:
  name: el-cd-listener
  namespace: default
spec:
  selector:
    app: cd-listener
  ports:
    - protocol: TCP
      port: 8080        # Exposing port 8080 to the outside world
      targetPort: 8080  # Forward traffic to port 8080 inside the container
  type: LoadBalancer    # This is crucial for provisioning the external IP
