apiVersion: v1
kind: Service
metadata:
  name: el-cd-listener
  namespace: default
spec:
  selector:
    app: cd-listener
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
