apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pipelinerun-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage   # or whatever class works in your cluster
