apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: cd-template
spec:
  params:
    - name: repository
      description: The git repository URL
      default: " "
    - name: branch
      description: The git branch to build
      default: "main"
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: "$(uid)-$(params.repository)-$(params.branch)"  # Dynamic naming based on parameters
        namespace: default
      spec:
        serviceAccountName: pipeline-sa
        pipelineRef:
          name: cd-pipeline  # Ensure this matches the name of your pipeline
        workspaces:
          - name: pipeline-workspace   # Match workspace name in pipeline.yaml
            persistentVolumeClaim:
              claimName: pipelinerun-pvc  # Ensure the PVC name matches
        params:
          - name: repo-url
            value: "$(params.repository)"  # Use the dynamic repository URL
          - name: branch
            value: "$(params.branch)"  # Use the dynamic branch from the webhook payload
          - name: build-image
            value: "docker.io/janithad/cicd-practice-local:latest"
          - name: app-name
            value: "my-python-service"
